# Generated by Django 3.2.12 on 2022-04-01 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('comment', models.CharField(max_length=255)),
                ('state', models.BooleanField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hete.clients')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hete.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_time', models.DateTimeField()),
                ('zone', models.URLField()),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hete.clients')),
                ('order', models.ManyToManyField(to='hete.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.URLField()),
                ('state', models.IntegerField(choices=[(0, 'Preparandose'), (1, 'Entregandose'), (2, 'Pagado'), (3, 'Deuda')])),
                ('dispatcher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hete.dispatcher')),
                ('order', models.ManyToManyField(to='hete.Order_details')),
            ],
        ),
    ]
