# Generated by Django 3.2.12 on 2022-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hete', '0002_distribution_order_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='house_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
